### PR TITLE
Bug 1877368: Disable Helm Chart Install form and show error alert if chart is not reachable

### LINKED ISSUE #5190: HELM - Console displays 'Install Helm Chart' screen w/o values.yaml when index.yaml points to invalid tgz path
When installing helm chart from OCP developer catalog if the helm repo index.yaml points to invalid location the install screen is displayed without values (tgz can't be found) and no error message.   

image

@pedjak

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Jira: https://issues.redhat.com/browse/ODC-4360
Fixes #5190

**Screenshot:**
image

**Unit Tests Coverage:**
image

/kind bug

### CODE REVIEW

File: frontend/packages/dev-console/src/components/helm/HelmInstallUpgradePage.tsx [hunk 1]
```diff
@@ -87,9 +88,12 @@ const HelmInstallUpgradePage: React.FunctionComponent<HelmInstallUpgradePageProp
...
     const fetchHelmRelease = async () => {
       let res;
+      let error: Error = null;
       try {
         res = await coFetchJSON(config.helmReleaseApi);
-      } catch {} // eslint-disable-line no-empty
+      } catch (e) {
+        error = e;
+      } // eslint-disable-line no-empty
       if (ignore) return;
```
Comment (abhinandan13jan) [inline frontend/packages/dev-console/src/components/helm/HelmInstallUpgradePage.tsx:97]: just a query. Why do we have this `ignore` check after the coFetch and not before it?

Comment (divyanshiGupta) [reply frontend/packages/dev-console/src/components/helm/HelmInstallUpgradePage.tsx:97]: Okay I will try to explain it briefly. So we do this to prevent updating a state of an unmounted component and as you can see the state is being updated only after the API call.

**Review by rohitkrai03 — CHANGES_REQUESTED** [review]
I think chart version dropdown should be hidden if there's no chart version present. Empty dropdown feels odd here. @parvathyvr WDYT?

**Comment by andrewballantyne** [comment]
> I think chart version dropdown should be hidden if there's no chart version present. Empty dropdown feels odd here. @parvathyvr WDYT?

Do we have placeholders? I wonder if "No versions available" or something akin to that is better... Just wondering if removing the input item, labels et all is going to leave more of a void in the UI.

**Review by parvathyvr — COMMENTED** [review]
I agree with @rohitkrai03  that the empty dropdown looks odd.In the original mockup screen attached in the bug [ODC-4360](https://issues.redhat.com/browse/ODC-4360) I had the Chart Version dropdown although disabled ,showing the latest chart version/app version.But if we do not have this data to show, my opinion would be in lines with what @andrewballantyne  suggested above.I think if we do not have data to show in the ‘Chart Version’ dropdown we can show ‘Not available’ in the disabled dropdown. CC @beaumorley

**Comment by rohitkrai03** [comment]
@parvathyvr Do you think we should also add the http error that we get back from backend to the alert. I tried it with a private helm chart that is not accessible and it looks something like this - 
image

**Comment by parvathyvr** [comment]
@rohitkrai03 I think giving more info about why the Helm chart is unavailable is a good addition!

> @parvathyvr Do you think we should also add the http error that we get back from backend to the alert. I tried it with a private helm chart that is not accessible and it looks something like this -
> 
> Screenshot from 2020-09-10 21-23-27

**Comment by divyanshiGupta** [comment]
> @rohitkrai03 I think giving more info about why the Helm chart is unavailable is a good addition!
> 
> > @parvathyvr Do you think we should also add the http error that we get back from backend to the alert. I tried it with a private helm chart that is not accessible and it looks something like this -
> > Screenshot from 2020-09-10 21-23-27

@rohitkrai03 @parvathyvr done. PTAL.

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Review by parvathyvr — APPROVED** [review]
LGTM!
