### PR TITLE
Bug 1829052: Remove non-general 'Version' field from Installed Operators list page

### LINKED ISSUE #3967: Operand's version at .Status.Version instead of .Spec.Version
Some Operators, such as the Jaeger Operator, manage the version of their operands. As such, there's no `Version` field under the `Spec` node, but there is one under `Status` instead.

The console's UI should fallback to `.Status.Version` in case `.Spec.Version` is empty.

https://github.com/openshift/console/blob/0150aba43092ae28e7585de5119895352e34bce1/frontend/packages/operator-lifecycle-manager/src/components/operand.tsx#L151-L156

image

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @spadgett 
closes #3967

cc'ing @tlwu2013 

do we want 4.4 cherrypick ?

### CODE REVIEW

File: frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx [hunk 1]
```diff
@@ -130,7 +130,6 @@ const tableColumnClasses = [
   '',
   '',
   classNames('pf-m-hidden', 'pf-m-visible-on-sm', 'pf-u-w-16-on-lg'),
-  classNames('pf-m-hidden', 'pf-m-visible-on-lg'),
   classNames('pf-m-hidden', 'pf-m-visible-on-xl'),
   classNames('pf-m-hidden', 'pf-m-visible-on-2xl'),
```
Comment (spadgett) [inline frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx:134]: I wonder if we should adjust some of these other classes since we have a little more space.

File: frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx [hunk 2]
```diff
@@ -263,9 +256,6 @@ export const OperandTableRow: React.FC<OperandTableRowProps> = ({
       <TableData className={tableColumnClasses[2]}>
         <OperandStatus operand={obj} />
       </TableData>
-      <TableData className={tableColumnClasses[3]}>
-        {_.get(obj.spec, 'version') || <div className="text-muted">Unknown</div>}
```
Comment (spadgett) [inline frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx:267]: @tlwu2013 Do you think we should change operand status to show `-` if there is no value? It might look similarly broken for CRDs where it's not expected.

Comment (spadgett) [reply frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx:267]: (Instead of `Unknown` which is what it shows today.)

File: frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx (hunk 1 above)
Comment (spadgett) [reply frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx:134]: I pulled this down to test, and I think it's good as-is. Disregard.

File: frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx [hunk 3]
```diff
@@ -224,7 +217,7 @@ const getOperandStatus = (obj: K8sResourceKind): OperandStatusType => {
 export const OperandStatus: React.FunctionComponent<OperandStatusProps> = ({ operand }) => {
   const status: OperandStatusType = getOperandStatus(operand);
   if (!status) {
-    return <div className="text-muted">Unknown</div>;
+    return <div className="text-muted">-</div>;
```
Comment (spadgett) [inline frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx:220]: I don't think we use `text-muted` with `-` in other places.

```suggestion
    return <>-</>;
```

File: frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx (hunk 2 above)
Comment (tlwu2013) [reply frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx:267]: @spadgett That makes sense, thanks for catching this up!

File: frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx (hunk 3 above)
Comment (jhadvig) [reply frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx:220]: https://github.com/openshift/console/blob/master/frontend/public/components/persistent-volume-claim.jsx#L134

Comment (spadgett) [reply frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx:220]: @jhadvig You've found another outlier. Most places we *don't* add `text-muted` to the `-`. 

https://github.com/openshift/console/blob/master/frontend/public/components/container.tsx#L308

https://github.com/openshift/console/blob/master/frontend/public/components/machine-autoscaler.tsx#L107

https://github.com/openshift/console/blob/master/frontend/packages/dev-console/src/components/pipelines/list-page/PipelineRow.tsx#L45

etc

Comment (spadgett) [reply frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx:220]: @jhadvig In fact, the PVC example you linked to was just added recently in #4482, and we have other columns that have `-` without `text-muted` in the same table. That's probably not the example we should use.

Comment (spadgett) [reply frontend/packages/operator-lifecycle-manager/src/components/operand/index.tsx:220]: `text-muted` removed from the PVC table in #5382
